system = "x86_64-linux"

[user]
name = "grant"
description = "Grant Handy"

[apps]
pkgs = ["protonvpn-gui"]
pkgs-unstable = ["beeper"]
favorites = ["beepertexts.desktop"]

[git]
name = "grantshandy"
email = "granthandy@proton.me"

[firefox]
default-engine = "ddg"

extensions = [
    "ublock-origin",
    "darkreader",
    "proton-pass",
    "youtube-shorts-block",
    "return-youtube-dislikes",
]
bookmarks = [
    { name = "Mail", url = "https://mail.proton.me" },
    { name = "Calendar", url = "https://calendar.proton.me" },
    { name = "Spotify", url = "https://open.spotify.com" },
    { name = "GitHub", url = "https://github.com" },
    { name = "NixOS Wiki", url = "https://wiki.nixos.org/wiki/NixOS_Wiki" },
    { name = "Papago", url = "https://papago.naver.com" },
    { name = "Canvas", url = "https://utah.instructure.com" },
    { name = "Thesaurus", url = "https://www.powerthesaurus.org/" },
]

[firefox.engines]
homemanager = "https://home-manager-options.extranix.com/?query={s}&release=master"
hanjadict = "https://koreanhanja.app/{s}"
koverb = "https://koreanverb.app/?search={s}"

[[sync-device]]
name = "Phone"
id = "5IBK4XI-3SBE6A7-JCU7L3E-UB3W45N-SMPSC5C-HDHSVBG-UM6XUI6-HQHUSAA"
